fix: 10227 use dev config with modrun
hashgraph/hedera-services pull request #10249
Opened 2023-12-04 05:02 UTC by jamesnguyentech

Description:

This PR update modrun for running with the dev config.

Related issue(s):

Fixes https://github.com/hashgraph/hedera-services/issues/10227

2023-12-04 15:07 UTC, nathanklick requested changes

2023-12-04 15:27 UTC, jamesnguyentech commented on hedera-node/hedera-app/build.gradle.kts
> +        into(buildDir.dir("./lib"))
I reverted it. Copy it back into the data folder as before, then copy the entire folder into build/node.

2023-12-04 17:05 UTC, nathanklick commented on hedera-node/hedera-app/build.gradle.kts
> +        shouldRunAfter(tasks.named("copyApp"))
```suggestion
        shouldRunAfter(tasks.named("copyApp"))
        shouldRunAfter(tasks.named("copyLib"))
```

2023-12-04 17:05 UTC, nathanklick submitted a review, later dismissed

2023-12-04 17:09 UTC, nathanklick approved these changes

2023-12-05 02:45 UTC, nathanklick commented
@jamesnguyentech Would you please run `./gradlew spotlessApply` on your PR branch to resolve the spotless check failure?

2023-12-05 07:45 UTC, jamesnguyentech commented
@nathanklick I ran it. Could you check it again?

2023-12-07 03:13 UTC, nathanklick commented
@jamesnguyentech Looks great, as soon as the remaining test run finishes I will merge unless there is an error. The unit test failure is a known issue which has already been fixed in the latest `develop` branch so I will bypass the failure.

2023-12-07 03:29 UTC, merged