Fix failing regression tests
hashgraph/hedera-services pull request #10298
Opened 2023-12-05 19:31 UTC by Neeharika-Sompalli

WIP

Fixes #10253 
Fixes #10254

2023-12-05 23:28 UTC, kimbor submitted a review, later dismissed
lgtm!

2023-12-06 15:31 UTC, JeffreyDallas requested changes
The tests are still failing due to `HapiGetAccountDetails` returns `NOT_SUPPORTED`

https://swirldslabs.slack.com/archives/C03G7CBJJ06/p1701875676568189
https://swirldslabs.slack.com/archives/C03G7CBJJ06/p1701809171622549

2023-12-07 03:06 UTC, tinker-michaelj approved these changes
LGTM, tyvm @Neeharika-Sompalli !

2023-12-07 15:48 UTC, kimbor approved these changes

2023-12-11 15:34 UTC, closed without merging