feat: use address book to determine node id
hashgraph/hedera-services pull request #10453
Opened 2023-12-12 21:16 UTC by kimbor

**Description**:
Change the way that node id is determined at startup from the command line.

**Related issue(s)**:

Fixes #10450

2023-12-13 23:00 UTC, nathanklick commented on platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/util/BootstrapUtils.java
> +        }
This check needs to move up to the `ServicesMain` class after we determine if there is a node ID passed in the command line args.

2023-12-14 13:11 UTC, jeromy-cannon submitted a review, later dismissed

2023-12-14 15:42 UTC, nathanklick submitted a review, later dismissed

2023-12-14 16:13 UTC, tinker-michaelj requested changes
This scans to me; but imo is too critical a change to commit without unit test coverage.

2023-12-14 16:14 UTC, Neeharika-Sompalli commented
> This scans to me; but imo is too critical a change to commit without unit test coverage.


➕  Agreed.

2023-12-14 16:17 UTC, nathanklick commented
> > This scans to me; but imo is too critical a change to commit without unit test coverage.
> 
> ➕ Agreed.

There's a limit to how much we can unit test the `main()` method, but we can cover the supporting methods. However, each and every HapiTest execution does exert testing of these methods (for at least the happy path).

2023-12-14 16:31 UTC, netopyr submitted a review, later dismissed
LGTM

2023-12-15 12:09 UTC, jeromy-cannon approved these changes

2023-12-15 16:05 UTC, tinker-michaelj approved these changes
LGTM, tyvm @kimbor !

2023-12-18 16:45 UTC, merged