docs: Cancun hip design document
hashgraph/hedera-services pull request #11253
Opened 2024-01-30 19:50 UTC by shemnon

**Description**:

Design document covering the HIPs for Cancun support in the EVM.

**Related issue(s)**:

documents #10272

**Notes for reviewer**:

Just a design doc

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-02-10 05:18 UTC, Nana-EC requested changes
Looking good.
I think a bit more detail would be useful.
The design docs value is that any dev should be able to pick it up and go ahead and implement, plus reviewers of PRs should be able to reference this and map the changes to the intentions here.

2024-02-10 05:18 UTC, Nana-EC commented on hedera-node/docs/design/services/smart-contract-service/cancun-fork-support.md
> +There Ethereum "Cancun" hard introduces a number of changes to the EVM that will need to be implemented to maintain EVM
```suggestion
The Ethereum "Cancun" hardfork introduces a number of changes to the EVM that will need to be implemented to maintain EVM
```

2024-02-10 05:18 UTC, Nana-EC commented on hedera-node/docs/design/services/smart-contract-service/cancun-fork-support.md
> +Equivalence. There are four different HIPs covering this feature (HIP-865: Add EVM Support for transient storage and
Should turn this into a list 
```suggestion
Equivalence. There are four different HIPs covering this feature 
- HIP-865: Add EVM Support for transient storage
- HIP-866: Add EVM compatibility for non-supported Cancun blob features
- HIP-867: Add Smart Contract Services Support for KZG Point Evaluation Precompiled Function
- HIP-868: Support Cancun Self-Destruct
```

2024-02-10 05:18 UTC, Nana-EC commented on hedera-node/docs/design/services/smart-contract-service/cancun-fork-support.md
> +### Example User Story
Let's have more specific user stories highlighting the capabilities to users

2024-02-10 05:18 UTC, Nana-EC commented on hedera-node/docs/design/services/smart-contract-service/cancun-fork-support.md
> +A new EVM version will be created that will be based off of the Cancun EVM. Simply activating the Cancun EVM should get
Cna we be explicit on what activating means? E.g. what config needs to be xhanged and to what?

2024-02-10 05:18 UTC, Nana-EC commented on hedera-node/docs/design/services/smart-contract-service/cancun-fork-support.md
> +that `versionedHashes` is st to an empty list and that `blobGasPrice` is set to one. We should be able to do that in all
```suggestion
that `versionedHashes` is set to an empty list and that `blobGasPrice` is set to one. We should be able to do that in all
```

2024-02-10 05:18 UTC, Nana-EC commented on hedera-node/docs/design/services/smart-contract-service/cancun-fork-support.md
> +that `versionedHashes` is st to an empty list and that `blobGasPrice` is set to one. We should be able to do that in all
Set them in the EVM versions how? Is there a specific class that needs to be updated or a a method that needs to be overrided?

2024-02-10 05:18 UTC, Nana-EC commented on hedera-node/docs/design/services/smart-contract-service/cancun-fork-support.md
> +Either with a new class or a class that takes a constructor parameter, update the HederaSelfDestructOperation so that it
Please specify which option the implementation should follow. Feel free to not that the other wasn't chosen for reason X

2024-02-29 00:17 UTC, david-bakin-sl commented
The commit I just pushed addresses _some_ PR review comments; not all.  The remaining comments are actually _inline_ in the document as HTML comments - this is to facilitate my updating the document in my repo clone.  They'll be properly removed when they're addressed.

2024-05-03 17:23 UTC, shemnon commented
Closing as stale.  If needed @david-bakin-sl  or @Nana-EC can re-create the PR.

2024-05-03 17:23 UTC, closed without merging

2024-05-03 17:25 UTC, Nana-EC commented
> Closing as stale. If needed @david-bakin-sl or @Nana-EC can re-create the PR.

Thanks @shemnon. Cancun support should be going out in Hedera 0.50.0, appreciate the leadership and contribution here.