test: six new hapi tests for token claim airdrop
hashgraph/hedera-services pull request #14811
Opened 2024-08-13 12:58 UTC by povolev15

Implemented 3 tests:
-TokenClaimAirdrop transaction containing duplicate entries should fail
-TokenClaimAirdrop transaction with more than 10 pending airdrops entries should fail
-TokenClaimAirdrop transaction with no pending airdrops entries should fail
-[Single Token]
Given existing pending airdrop in state when valid TokenClaimAirdrop transaction containing 1 entry for the same pending airdrop is performed then the TokenClaimAirdrop should succeed
-[Single Token]
Receiver (a normal account) signs a pending TokenClaimAirdrop transaction for FT A 
-[Single Token]
Receiver (a normal account) signs a pending TokenClaimAirdrop transaction for 1 NFT A with serial number 1
-[Single Token]
Receiver signs a TokenClaimAirdrop with not enough HBAR, then gets enough HBAR and claims the same airdrop again.
**Related issue(s)**:

Fixes #14703 
#14701 
#14700 
#14813 
#14814
#14815 
#14816

2024-08-13 14:01 UTC, ibankov commented on hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java
> +import com.hederahashgraph.api.proto.java.TokenType;
wrong import

2024-08-13 14:03 UTC, ibankov commented on hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java
> +                tokenClaimAirdrop().hasPrecheck(EMPTY_PENDING_AIRDROP_ID_LIST));
Do you need all the accounts and tokens created to do claim with empty body, this should be a pureCheck so you can simpify this test to tokenClaimAirdrop().hasPrecheck(EMPTY_PENDING_AIRDROP_ID_LIST)

2024-08-13 14:05 UTC, ibankov commented on hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java
> +                        .tokenType(FUNGIBLE_COMMON)
you can create a helper method that creates a token and/or moves a token to reduce code duplication

2024-08-13 17:39 UTC, david-bakin-sl approved these changes
LGTM

2024-08-13 17:39 UTC, david-bakin-sl commented on hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java
> +    private static final String FUNGIBLE_TOKEN = "fungibleToken";
Why not name this `FUNGIBLE_TOKEN_1` to match the rest?

2024-08-14 10:38 UTC, JivkoKelchev requested changes

2024-08-14 10:38 UTC, JivkoKelchev commented on hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java
> +    }
There is no need to send airdrops in this case.
Here, when you send claim transaction, it should fail in the `pureChecks` with PENDING_AIRDROP_ID_REPEATED, so no state checks.

This way the test will be way simpler and easy to read
```suggestion
    @HapiTest
    @DisplayName("token claim with duplicate entires should fail")
    final Stream<DynamicTest> duplicateClaimAirdrop() {
        return hapiTest(
                cryptoCreate(RECEIVER).balance(ONE_HUNDRED_HBARS),
                tokenClaimAirdrop(
                                pendingAirdrop(OWNER, RECEIVER, FUNGIBLE_TOKEN),
                                pendingAirdrop(OWNER, RECEIVER, FUNGIBLE_TOKEN))
                        .payingWith(RECEIVER)
                        .feeUsd(0.001)
                        .hasPrecheck(PENDING_AIRDROP_ID_REPEATED));
    }
```

2024-08-14 10:38 UTC, JivkoKelchev commented on hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java
> +                        .initialSupply(1000L),
OWNER and FUNGIBLE_TOKEN are already created in `beforeAll()`. You can use them directly.

2024-08-14 10:38 UTC, JivkoKelchev commented on hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java
> +                        .hasPrecheck(PENDING_NFT_AIRDROP_ALREADY_EXISTS));
`PENDING_NFT_AIRDROP_ALREADY_EXISTS` was wrong status.
It was replaced with `PENDING_AIRDROP_ID_REPEATED`. 
You may need to rebase or merge the target branch.

2024-08-14 15:59 UTC, kimbor commented on hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java
> +    @DisplayName("token claim with duplicate entires should fail")
```suggestion
    @DisplayName("token claim with duplicate entries should fail")
```

2024-08-15 12:09 UTC, ibankov approved these changes
LGTM

2024-08-15 12:36 UTC, JivkoKelchev approved these changes
LGTM, thanks @povolev15

2024-08-15 13:00 UTC, merged