ci: Updating the publish to Codacy step to be skipped on forked PRs.
hashgraph/hedera-services pull request #15433
Opened 2024-09-11 10:31 UTC by san-est

**Description**:
Codecy reporter needs additional parameters to be skipped on forked PRs so that steps/actions which require the use of secrets are only ran on PRs from the original repo.

**Related issue(s)**:

Fixes #14293 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-09-11 13:06 UTC, nathanklick requested changes

2024-09-11 13:06 UTC, nathanklick commented on .github/workflows/node-zxc-compile-application-code.yaml
> +        if: ${{ inputs.enable-unit-tests && !cancelled() && github.event.pull_request.head.repo.full_name == github.repository }}
```suggestion
        if: ${{ inputs.enable-unit-tests && !cancelled() &&  !github.event.pull_request.head.repo.fork }}
```

2024-09-11 14:12 UTC, san-est commented on .github/workflows/node-zxc-compile-application-code.yaml
> +        if: ${{ inputs.enable-unit-tests && !cancelled() && github.event.pull_request.head.repo.full_name == github.repository }}
I've updated to the suggested change.

2024-09-17 13:02 UTC, rbarkerSL approved these changes
LGTM

2024-09-17 13:04 UTC, nathanklick submitted a review, later dismissed

2024-10-22 12:46 UTC, san-est commented
Closing pull request due to old conflicts which caused issues with the forked branch. Will open a new PR for the same.

2024-10-22 12:46 UTC, closed without merging

2024-10-22 13:03 UTC, san-est commented
New PR: #16078