Hip18 m token create
hashgraph/hedera-services pull request #1643
Opened 2021-06-21 18:29 UTC by anighanta

**Related issue(s)**:
Addresses #1593 

**Summary of the change**:
Add the customFeesKey and customFees form the TokenCreate transaction request to the created Merkle Token.

**External impacts**:
Uses can now set custom fees when creating a token so that when ever that token is transferred that custom fee is paid by the payer of that token transfer transaction to the `feeCollector` mentioned in the customFee - refer [HIP-18](https://github.com/hashgraph/hedera-improvement-proposal/blob/master/HIP/hip-18.md)

2021-06-21 18:49 UTC, tinker-michaelj requested changes
These are the right places to change! But 95% of the work in this issue is validating the custom fee schedule. 

At minimum, we want to add a property like, `tokens.maxCustomFeesAllowed` and check,
1. Are there no more than the allowed number of custom fees?
2. Are all the mentioned fee collection accounts usable?
3. Are all the mentioned non-ℏ denominations usable?
4. Are the fractions valid in any fractional fees?

If anything is not valid, we want to abort with a meaningful `ResponseCode`---not simply ignore the fee schedules.

We can take some time after scrum to consider how to write some of the unit tests for this, since it can be **quite** tricky to do so with `HederaTokenStore`.

2021-06-21 18:49 UTC, tinker-michaelj commented on hedera-node/src/main/java/com/hedera/services/state/submerkle/CustomFee.java
> +	public static CustomFee mapFromGrpc(final CustomFeesOuterClass.CustomFee customFeeFromRequest) {
We can use the [`CustomFee.fromGrpc()` factory](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/state/submerkle/CustomFee.java#L104) here instead. (This `mapFromGrpc()` method will not work quite right for fixed fees with ℏ denom, or fractional fees without a maximum value set.)

2021-06-21 18:49 UTC, tinker-michaelj commented on hedera-node/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
> +			var customFeesFromRequest = request.getCustomFees().getCustomFeesList();
As above, can use the `CustomFee.fromGrpc()` factory.

2021-06-22 15:41 UTC, anighanta commented
Posted a question about associating the `feeCollector` in `FractionalFee` to the token being created [here](https://github.com/hashgraph/hedera-improvement-proposal/discussions/92#discussioncomment-905626)

2021-06-22 19:21 UTC, tinker-michaelj reviewed
Known TODOs:
- [ ] Validate `customFeeKey` in `TokenCreateTransitionLogic`.
- [ ] Add EET support for `customFeeKey` in creation/getInfo verbs.

2021-06-22 19:24 UTC, tinker-michaelj reviewed
<duplicate>

2021-06-22 22:09 UTC, tinker-michaelj approved these changes
LGTM

2021-06-22 22:22 UTC, qnswirlds approved these changes
Overall LGTM. Just a minor note that we may want to use a simple `for` loop in lieu of `stream()`.

2021-06-23 03:16 UTC, ljianghedera approved these changes
LGTM

2021-06-23 04:35 UTC, merged