chore: Move `overwrites.yaml` to config directory
hashgraph/hedera-services pull request #17178
Opened 2024-12-30 15:28 UTC by timo0

Fix #17164 

* Renamed `overwrites.yaml` to `node-overwrites.yaml` to clarify the purpose
* Moved from root directory to `data/config` directory 
* Renamed `networkEndpoints` to `interfaceBindings`

2024-12-30 15:33 UTC, edward-swirldslabs commented on platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/config/GossipConfig.java
>       * @param nodeId the node ID
The comments on this method need to be updated to reflect the field name change.

2024-12-30 15:33 UTC, edward-swirldslabs commented on platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/config/GossipConfig.java
> +        @ConfigProperty(defaultValue = Configuration.EMPTY_LIST) List<NetworkEndpoint> interfaceBindings,
Could be add  class level javadoc explaining the the meaning and purpose of each parameter?

2024-12-30 16:13 UTC, nathanklick requested changes

2024-12-30 16:13 UTC, nathanklick commented on platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformBuildConstants.java
> +    public static final String DEFAULT_OVERWRITE_YAML_FILE_NAME = "data/config/node-overwrites.yaml";
```suggestion
    public static final String DEFAULT_OVERWRITE_YAML_FILE_NAME = "data/config/node-overrides.yaml";
```

2024-12-30 17:04 UTC, timo0 commented on platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformBuildConstants.java
> +    public static final String DEFAULT_OVERWRITE_YAML_FILE_NAME = "data/config/node-overwrites.yaml";
added manually

2024-12-30 17:07 UTC, edward-swirldslabs approved these changes

2024-12-31 17:05 UTC, nathanklick approved these changes

2024-12-31 18:14 UTC, mhess-swl approved these changes
Services changes look good 👍

2024-12-31 23:26 UTC, merged