E2E: Transfer Precompiles and Child Records Checks
hashgraph/hedera-services pull request #2607
Opened 2021-12-14 15:40 UTC by georgiyazovaliiski

**Description**:
This PR adds:
1. E2E scenarios for the transferTokens, transferNft, transferNfts.
2. ChildRecords checks in the HAPI testing suite.

**Checklist**

- [x] Tested (unit, integration, etc.)

2021-12-14 16:39 UTC, tinker-michaelj commented on hedera-node/settings.txt
> -reconnect.asyncInputStreamTimeoutMilliseconds, 60000
This property has been renamed to,
```
reconnect.asyncStreamTimeoutMilliseconds, 60000
```

2021-12-14 16:45 UTC, tinker-michaelj approved these changes
LGTM so far!

2021-12-15 08:21 UTC, stoqnkpL requested changes

2021-12-15 08:21 UTC, stoqnkpL commented on test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ChildRecordsAsserts.java
> +public class ChildRecordsAsserts extends TransactionRecordAsserts {
Do we need this class at all?

2021-12-15 08:21 UTC, stoqnkpL commented on hedera-node/settings.txt
> -reconnect.asyncInputStreamTimeoutMilliseconds, 60000
Why do we need to remove this?

2021-12-15 08:21 UTC, stoqnkpL commented on test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetTxnRecord.java
> +					" be the same size.");
```suggestion
```suggestion
assertEquals(expectedChildRecords.size(), actualRecords.size(), 
					String.format("Expected %d child records, got %d", expectedChildRecords.size(), actualRecords.size()));
```
```

2021-12-15 08:21 UTC, stoqnkpL commented on test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetTxnRecord.java
> +
we should delete this

2021-12-16 08:36 UTC, stoqnkpL approved these changes
LGTM!

2021-12-21 16:43 UTC, tinker-michaelj approved these changes
LGTM!!

2021-12-22 06:36 UTC, merged