Precompiles E2E: HSCS-PREC-008
hashgraph/hedera-services pull request #2711
Opened 2022-01-10 06:51 UTC by georgiyazovaliiski

**Description**:
This PR might still not be ready.

2022-01-10 11:27 UTC, stoqnkpL requested changes
Overall looks good but I think some more changes are required.
⚠️ There's a failing test in CryptoCreateSuite (xferRequiresCrypto()) that causes ci-cd to fail. It's not failing in `hts-contracts` branch.

2022-01-10 11:27 UTC, stoqnkpL commented on test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractHTSSuite.java
> +									/* --- HSCS-PREC-009 --- */
This should be /* --- HSCS-PREC-008 --- */

2022-01-10 11:27 UTC, stoqnkpL commented on test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractHTSSuite.java
> +													.alsoSigningWithFullPrefix(FEE_COLLECTOR)
We should not need the FEE COLLECTOR signature, I think we can remove it

2022-01-10 11:27 UTC, stoqnkpL commented on test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractHTSSuite.java
> +												changingFungibleBalances()
In the child rec we also have `assessed_custom_fees` and `transferList`, can we also assert their correct values?

2022-01-10 11:27 UTC, stoqnkpL commented on test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractHTSSuite.java
> +						getAccountBalance(FEE_COLLECTOR).hasTinyBars(1000000100)
This should be 100.

2022-01-10 11:27 UTC, stoqnkpL commented on test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractHTSSuite.java
> +						cryptoCreate(FEE_COLLECTOR),
We should create the FEE_COLLECTOR account with intial balance of 0, this way we can assert it has a balance ot 100 at the end of the test; 1000000100 is not very clear

2022-01-13 07:52 UTC, stoqnkpL approved these changes
LGTM

2022-01-14 01:09 UTC, shemnon approved these changes
LGTM

Curious as to why the gas prices went up in the EET tests as there were no gas schedule changes.  Is it just to have them all be the same?

2022-01-14 03:58 UTC, stoqnkpL commented
> LGTM
> 
> Curious as to why the gas prices went up in the EET tests as there were no gas schedule changes. Is it just to have them all be the same?

Prices went up because the intrinsic gas PR got merged. And they weren't fixed there, because these EETs were part of other PRs that were merged right before/after that.

2022-01-14 20:06 UTC, shemnon approved these changes

2022-01-16 21:47 UTC, tinker-michaelj requested changes
Although this does let contracts be fee collectors, it **also** lets `ContractID`s be used directly in a `CryptoTransferTransactionBody`, which Product has previously disallowed. 

I'm double-checking which direction we want to go. 👍

2022-01-17 04:49 UTC, tinker-michaelj approved these changes
Confirmed with Product that we're now OK with using `ContractID`s in the `CryptoTransferTransactionBody`. 👍

2022-01-17 04:49 UTC, merged