03332 erc20 transferFrom bug
hashgraph/hedera-services pull request #3353
Opened 2022-05-12 11:05 UTC by tdermendzhievv

**Description**:
This PR provides fix for the bug where during the execution of the transferFrom precompile the allowances of the spender are not updated.
Also getMinimumFeeInTinybars method is revised for approve and set approval for all precompiles

**Related issue(s)**: #3332

2022-05-12 13:13 UTC, stoqnkpL requested changes
Looks good overall, great catch on the fee calculation.
I think we should use `msg.sender` instead of the `payer` as the `spender` account in the case of a `transferFrom` from the precompile. This way whoever called the precompiled contract will be considered the spender and not the account that initiated the Hedera transaction. Also, we should make sure the signatures are checked correctly and have an E2E test that validates at least the straight-case scenario

2022-05-12 17:22 UTC, tinker-michaelj commented on hedera-node/src/main/java/com/hedera/services/ledger/BalanceChange.java
> +		tokenChange.isApprovedAllowance = aa.getIsApproval();
The constructor already sets this field.

2022-05-12 18:00 UTC, stoqnkpL commented
Pushed a commit that:
- Adds an exception to signatures verification for transfers when using the granted allowance
- Creates `BalanceChange` types using the message sender instead of Transaction payer as payerId
- Adds E2E for ERC20 transferFrom simplest case scenario

What is still pending:
- construct NFT changes correctly using approvals
- add E2E for NFT scenario as well
- I noticed some of the E2E tests from `ERCPrecompileSuite` are failing 😞 maybe it's related to the changes we're doing to test-clients but we need to investigate

2022-05-13 19:01 UTC, shemnon approved these changes

2022-05-13 21:42 UTC, tinker-michaelj approved these changes
LGTM for now, grinding through a full test matrix - https://github.com/hashgraph/hedera-services/issues/3382

2022-05-13 21:43 UTC, merged