feat: disable ethereumj log
hashgraph/hedera-services pull request #3493
Opened 2022-06-03 08:37 UTC by IvanKavaldzhiev

**Description**:
As @JeffreyDallas recommended in a comment on #3077 , this PR will disable ethereumj library to create log files by overriding the logback.xml from the library. After we completely remove the depedency from test-clients this logback.xml file can also be deleted.

**Related issue(s)**: #3077 

Fixes #

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-06-03 14:56 UTC, stoqnkpL approved these changes
LGTM!

2022-06-03 15:17 UTC, JeffreyDallas commented
It did not resolve the issue, test still failing

2022-06-03 15:25 UTC, JeffreyDallas requested changes

2022-06-03 15:25 UTC, JeffreyDallas commented on test-clients/src/main/resource/logback.xml
> +
Test still failing.

2022-06-04 00:05 UTC, JeffreyDallas approved these changes

2022-06-04 00:05 UTC, JeffreyDallas commented
Test passed

https://swirldslabs.slack.com/archives/C03ELH5MUHK/p1654297794795799

2022-06-04 14:38 UTC, merged