Help to debug node liveness timeout
hashgraph/hedera-services pull request #3745
Opened 2022-08-01 19:08 UTC by JeffreyDallas

Help to debug regression issue 2669

https://github.com/swirlds/swirlds-platform-regression/issues/2669

Test result

https://swirldslabs.slack.com/archives/C03ELH5MUHK/p1659386022872099

https://swirldslabs.slack.com/archives/C03ELH5MUHK/p1659388229224179

2022-08-04 14:24 UTC, Neeharika-Sompalli requested changes
The

2022-08-04 14:24 UTC, Neeharika-Sompalli commented on .circleci/config.yml
> +        default: "hedera-regression-test"
This change debug purposes should be added to a separate branch

2022-08-04 15:37 UTC, qnswirlds submitted a review, later dismissed

2022-08-05 16:32 UTC, Neeharika-Sompalli approved these changes

2022-08-07 20:03 UTC, merged