HederaEvmContractAliases
hashgraph/hedera-services pull request #4054
Opened 2022-10-13 14:46 UTC by mustafauzunn

**Description**:

Extract needed logic from contract aliases in evm module and adapt hedera-mono-service to use it

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

This PR will be merged after extract-evm-core-logic-mono-service

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-10-14 20:02 UTC, Nana-EC approved these changes

2022-10-17 11:54 UTC, IvanKavaldzhiev approved these changes
LGTM

2022-10-21 16:33 UTC, qnswirlds approved these changes
LGTM overall. Some of the files have different license header.

2022-10-25 17:07 UTC, shemnon requested changes

2022-10-27 20:37 UTC, shemnon approved these changes

2022-10-28 16:54 UTC, nathanklick approved these changes
Approved with respect to the Gradle and JPMS module changes only.

2022-10-31 07:52 UTC, merged