Docker gradle setup
hashgraph/hedera-services pull request #4431
Opened 2022-12-07 12:59 UTC by hendrikebbers

All docker tasks are defined as gradle tasks.

<img width="468" alt="docker" src="https://user-images.githubusercontent.com/9443847/206185575-7aff7c88-1dfe-4e85-a9eb-ad502fd26b68.png">

2022-12-07 13:06 UTC, hendrikebbers commented
@nathanklick @JeffreyDallas this PR creates Gradle tasks for all docker workflows. While it works fine on my machine I have some questions regarding CI/CD & DevOps:

How is the docker-compose started in GitHubActions? I only found the task that creates the image?
Do we need to change the circleCI scripts?

2022-12-07 14:24 UTC, nathanklick requested changes
This PR breaks the CI pipeline.

2022-12-07 14:24 UTC, nathanklick commented on build.gradle.kts
> +    description = "Pushes the current tag of the docker image to the google registry"
We should be pushing this image. It is deprecated and will eventually be removed from the registry. 

This needs to be removed as we do not want anyone pushing by accident.

2022-12-07 23:10 UTC, mhess-swl commented on docker/README.md
> +All docker workflows are defined and gradle tasks. No skript of file in this folder should be called 'by hand'.
```suggestion
All docker workflows are defined with a corresponding gradle task. No script or file in this folder should be called 'by hand'.
```

2022-12-09 22:39 UTC, mhess-swl approved these changes

2022-12-20 17:11 UTC, mhess-swl approved these changes

2023-01-05 18:43 UTC, mhess-swl approved these changes

2023-01-09 20:21 UTC, nathanklick requested changes
We should use a proper Gradle plugin to manage the docker image builds:

Some examples of well-established and supported plugins:
- https://github.com/bmuschko/gradle-docker-plugin
- https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin

2023-01-10 06:44 UTC, hendrikebbers commented
@nathanklick I looked at Docker plugins and I assume that using one of them will end in more changes in the repo than the current PR. I wanted to change as less in the workflow as possible. I'm with you that using a docker plugin instead of the exec plugin should be the preferred way and would propose to do it as a next step. I will create an issue for that.

2023-01-10 09:05 UTC, nathanklick approved these changes

2023-01-10 15:09 UTC, merged