expand diagram
hashgraph/hedera-services pull request #5731
Opened 2023-03-21 11:16 UTC by lpetrovic05

closes #5678

2023-03-21 16:40 UTC, alittley requested changes
In addition to the `drawio` file being updated, the `html` must be re-exported

2023-03-22 14:32 UTC, cody-littley commented
> In addition to the `drawio` file being updated, the `html` must be re-exported

I hate this requirement. It's like being forced to commit compiled code. :(

2023-03-23 09:58 UTC, lpetrovic05 commented
> In addition to the `drawio` file being updated, the `html` must be re-exported

done

2023-03-23 13:09 UTC, alittley approved these changes

2023-03-23 16:40 UTC, netopyr approved these changes

2023-03-24 11:39 UTC, merged