Fix `SerializationTest`
hashgraph/hedera-services pull request #5903
Opened 2023-03-30 21:58 UTC by tinker-michaelj

**Description**:
 - Avoids stealing leading bytes from following `SelfSerializable`'s by only using PBJ schemas and parsers on `byte[]` instead of wrapped `SerializableDataInput/OutputStream`'s.

2023-03-31 00:25 UTC, Neeharika-Sompalli approved these changes
LGTM !

2023-04-03 07:21 UTC, hendrikebbers commented on hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/StateUtils.java
> +        final var length = in.readInt();
Null checks missing

2023-04-03 07:21 UTC, hendrikebbers commented on hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/StateUtils.java
> +        final var baos = new ByteArrayOutputStream();
baos is never closed

2023-04-03 07:21 UTC, hendrikebbers commented on hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/StateUtils.java
> +            @NonNull final T data, @NonNull final Codec<T> codec, @NonNull final SerializableDataOutputStream out)
null Checks missing

2023-04-03 07:21 UTC, hendrikebbers commented on hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/StateLifecyclesTest.java
> +        final var merkleState = tracked(new MerkleHederaState((t, s) -> {}, (e, m, p) -> {}, (s, p, ds, t, v) -> {}));
can you extract the params. This line is not really readable.

2023-04-03 07:21 UTC, hendrikebbers commented on hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/StateLifecyclesTest.java
> +                com.swirlds.common.io.exceptions.ClassNotFoundException.class,
Can you import the class?

2023-04-13 15:07 UTC, edward-swirldslabs approved these changes
I am code reviewing the 1 line addition in the SettingConstant.java file to which platform-hashgraph team is a code-owner.  I have seen the code change, have no objections, but cannot weigh in on the validity or correctness of the rest of the merge request.

2023-04-13 15:19 UTC, poulok commented on platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SettingConstants.java
> +    static final boolean TRANS_THROTTLE_DEFAULT_VALUE = false;
`transThrottle` has been removed from the baseline

2023-04-21 15:17 UTC, nathanklick requested changes
Javadoc syntax errors need to be corrected as it breaks the build. Merge conflicts need resolution.

2023-05-02 15:48 UTC, tinker-michaelj commented
Obsolete.

2023-05-02 15:48 UTC, closed without merging