Minor changes in the readme based on the new platform modules
hashgraph/hedera-services pull request #5976
Opened 2023-04-05 09:55 UTC by hendrikebbers

Minor changes in the readme based on the new platform modules

2023-04-21 15:19 UTC, nathanklick requested changes

2023-04-21 15:19 UTC, nathanklick commented on README.md
> +JDK 17 is required. The Temurin builds of [Eclipse Adoptium](https://adoptium.net/de/) are strongly recommended.
We should not link users to the German Adoptium site. 

```suggestion
JDK 17 is required. The Temurin builds of [Eclipse Adoptium](https://adoptium.net/) are strongly recommended.
```

2023-05-15 21:58 UTC, nathanklick approved these changes

2023-06-16 09:42 UTC, timo0 approved these changes

2023-06-20 09:44 UTC, hendrikebbers commented
@tomzhenghedera can you approve this PR?

2023-06-20 16:00 UTC, merged