Cleanup of service api
hashgraph/hedera-services pull request #6175
Opened 2023-04-19 09:15 UTC by hendrikebbers

Removed several methods that are not needed

2023-04-19 13:07 UTC, iwsimon approved these changes
LGTM

2023-04-19 17:52 UTC, Neeharika-Sompalli approved these changes

2023-04-20 19:59 UTC, povolev15 submitted a review, later dismissed
LGTM

2023-04-21 06:39 UTC, netopyr commented on hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/Service.java
> -    String getServiceName();
I don't think it makes much sense to remove this method right now. We may have to put it back quite soon or replace it with very similar functionality.

2023-04-21 06:42 UTC, netopyr approved these changes
The part in `hedera-app-spi` LGTM.

Not sure though, if these changes make sense right now. I think quite soon, we will be in a position where we can define how services should be added dynamically. At that point, this whole area has to be adjusted anyway.

2023-04-21 15:27 UTC, nathanklick requested changes
Merge conflicts and failing E2E tests.

2023-05-02 23:45 UTC, mhess-swl commented
Merge conflict and failing integration test run

2023-05-09 19:46 UTC, timo0 approved these changes

2023-05-10 13:40 UTC, povolev15 approved these changes

2023-05-15 21:56 UTC, nathanklick approved these changes
Approval limited to the `module-info.java` changes only. Please seek other reviews.

2023-05-23 23:35 UTC, mhess-swl commented
Merge conflicts need resolved

2023-06-15 12:44 UTC, closed without merging