Retire old security model for smart contracts by changing HAPI signature-check block limit to LOW
hashgraph/hedera-services pull request #6773
Opened 2023-05-24 23:46 UTC by david-bakin-sl

**Description**:

Set `contracts.maxNumWithHapiSigsSuccess` to `0` to disable old security model.
Ensure (appropriate) unit tests check both low and high limits.

**Related issue(s)**:

Fixes #6767 

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-05-25 02:51 UTC, david-bakin-sl commented
Last commit has partial status.

End goal:  Get all current tests (bdd) to pass and have new tests for the case where the block cutoff is `0`.  (Instead of `10_000_000`.)

Current status:

* After changing the block limit to 0 the following tests, all in `LeakyContractTestsSuite`, failed to pass.  I started "fixing" them by overriding the property `CONTRACTS_MAX_NUM_WITH_HAPI_SIGS_ACCESS` from 0 back to `10_000_000`.

|test|current state with latest commit|
|:--:|:---|
|`createTokenWithInvalidRoyaltyFee`|pass|
|`createTokenWithInvalidFeeCollector`|pass|
|`fungibleTokenCreateWithFeesHappyPath`|pass|
|`nonFungibleTokenCreateWithFeesHappyPath`|pass|
|`createTokenWithInvalidFixedFeeWithERC721Denomination`|pass|
|`accountWithoutAliasCanMakeEthTxnsDueToAutomaticAliasCreation`|**fail** even with property overridden|
|`RequiresTopLevvelSignatureOrApprovalDependingOnControllingProperty`|pass|
|`transferWorksWithTopLevelSignatures`|no fix yet attempted, so still **fail**, but see note below|

Left to do:

* Get the last two failing tests to pass.  The problem with `transferWorksWithTopLevelSignatures` and why I left it to last is that that one test reports _three_ results - but I don't understand why (there are _four_ tests it seems embedded in it, not three).
* Write new tests (probably derived from the existing tests) to pair with each one of the tests above that properly tests the condition when the block limit is low, i.e., `0`.  These would be the only tests in the system that specifically test that (there are no unit tests for it, nor any such tests elsewhere AFAIK) so it's important.

2023-05-26 18:49 UTC, tinker-michaelj commented on hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/ERC20PrecompilesTest.java
> +    private enum WithHapiBlockLimit {
Interesting pattern!

2023-05-26 18:49 UTC, tinker-michaelj approved these changes
LGTM!

2023-06-05 10:07 UTC, timo0 requested changes

2023-06-06 14:46 UTC, closed without merging