Fix flaky behavior in busy time test.
hashgraph/hedera-services pull request #6937
Opened 2023-06-05 16:48 UTC by cody-littley

Closes #6792

2023-06-05 16:50 UTC, alittley submitted a review, later dismissed

2023-06-06 09:36 UTC, lpetrovic05 requested changes
I think this doesn't work for the following reason:

- buffer size==0, we set the state to not working
- item is null, the state doesnt change
- we return and start over
- we drain the buffer and there are items in it, so we start processing, and the state is still not working

2023-06-06 13:05 UTC, cody-littley commented
@lpetrovic05 you are correct, this was a bug. I've fixed it in the latest commit.

2023-06-06 14:35 UTC, edward-swirldslabs approved these changes

2023-06-06 19:52 UTC, cody-littley commented
superseded by https://github.com/hashgraph/hedera-services/pull/6974

2023-06-06 19:52 UTC, closed without merging