refactor: fix sonar issues
hashgraph/hedera-services pull request #7916
Opened 2023-08-09 08:20 UTC by vtronkov

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-08-09 09:59 UTC, vtronkov commented
Duplicated: https://github.com/hashgraph/hedera-services/pull/7895

2023-08-17 11:24 UTC, netopyr requested changes

2023-08-17 11:24 UTC, netopyr commented on hedera-node/cli-clients/src/main/java/com/hedera/services/cli/sign/AccountBalanceSigningUtils.java
> +                    "signAccountBalanceFile :: Failed to sign file [{}] with exception : [{}]%n", streamFileToSign, e);
`%n` needs to be removed IMO. It encodes a newline for `printf()` but is not needed anymore. Also, I think we should remove the placeholder for the exception.

Same below.

2023-08-17 15:44 UTC, netopyr requested changes
We need to put this PR on hold until we clarified if a CLI-tool is an exception and should print its output.

2023-08-23 13:12 UTC, merged