split previewnet into separate yaml file
hashgraph/hedera-services pull request #8006
Opened 2023-08-15 12:57 UTC by jeromy-cannon

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-08-16 15:21 UTC, jeromy-cannon commented on .github/workflows/node-zxc-build-release-artifact.yaml
> +      # TODO: validate artifact is present in DevOps GCP Bucket
remove #TODO

2023-08-28 17:21 UTC, nathanklick requested changes

2023-08-28 17:21 UTC, nathanklick commented on .github/workflows/node-zxc-build-release-artifact.yaml
> +        default: true
This forces almost every step to be conditional and is undesirable. Instead we should split the previewnet release out to separate reusable workflow.

2023-08-29 20:10 UTC, nathanklick approved these changes

2023-08-29 23:05 UTC, merged