Create fat jar with services CLI so it can be run standalone
hashgraph/hedera-services pull request #8519
Opened 2023-09-12 02:33 UTC by david-bakin-sl

**Description**:

Create a fat jar for the services cli so it can be run standalone.  Also a script
to run it with (script is a slight modification of `pcli.sh`.

All you need is to copy the fat jar and the script someplace (to the same directory)
and run the script from there.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (manual)

2023-09-12 13:19 UTC, jjohannes requested changes
The `shadowJar` task from the shadow plugin, that is already used here, is doing exactly what you need I believe. So I think we should just configure that one with the additional Manifest attributes.

Can you check if what you get after the changes I proposed is sufficient for you?

2023-09-12 13:19 UTC, jjohannes commented on hedera-node/cli-clients/build.gradle.kts
> +
```suggestion
```

This does not do anything

2023-09-12 13:19 UTC, jjohannes commented on hedera-node/cli-clients/build.gradle.kts
> +}
```suggestion
tasks.shadowJar {
    manifest {
        attributes("Main-Class" to "com.swirlds.cli.PlatformCli", "Multi-Release" to "true")
    }
}

tasks.assemble {
    dependsOn(tasks.shadowJar)
}
```

2023-09-12 17:30 UTC, david-bakin-sl commented on hedera-node/cli-clients/build.gradle.kts
> +
removed

2023-09-12 17:30 UTC, david-bakin-sl commented on hedera-node/cli-clients/build.gradle.kts
> +}
thank you! works, implemented

2023-09-12 17:37 UTC, jjohannes approved these changes

2023-09-12 20:23 UTC, JeffreyDallas approved these changes

2023-09-12 20:46 UTC, qnswirlds approved these changes

2023-09-13 15:04 UTC, tinker-michaelj approved these changes
LGTM!

2023-09-13 15:14 UTC, jasperpotts approved these changes

2023-09-13 15:16 UTC, merged