Scheduled Transactions: MerkleSchedule
hashgraph/hedera-services pull request #853
Opened 2020-12-09 10:32 UTC by failfmi

**Related issue(s)**:
Closes #None

**Summary of the change**:
* Add MerkleSchedule
* State: Add FCMap<MerkleEntityId, MerkleSchedule>

**External impacts**:
None.

**Applicable documentation**
- [ ] Javadoc
- [ ] HAPI protobuf comments
- [ ] README

2020-12-14 15:07 UTC, tinker-michaelj requested changes
Looks great overall, made some comments to avoid future work needed to remove obsolete code elements. 👍

2020-12-15 13:50 UTC, failfmi commented on hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleSchedule.java
> +    @Deprecated
Will resolve the issue in a separate PR.

2020-12-15 20:26 UTC, tinker-michaelj approved these changes
LGTM

2020-12-15 20:26 UTC, tinker-michaelj commented on hedera-node/src/main/java/com/hedera/services/ServicesState.java
> +			log.info("Created scheduled txs FCMap after <= 1.0.0 state restoration");
In a future PR could fix typo `<= 1.0.0` as `<=0.10.0`. 👍

2020-12-15 22:37 UTC, tinker-michaelj commented
After running CodeCov, we need to add unit tests before that check will pass - see above.

2020-12-15 23:23 UTC, tinker-michaelj approved these changes
LGTM...seems as if CodeCov isn't picking up all the test coverage after running CI, will see what happens next.

2021-01-05 18:32 UTC, merged