Fix `TokenManagementSpecsStateful` tests
hashgraph/hedera-services pull request #8555
Opened 2023-09-13 08:44 UTC by natanasow

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-09-13 12:31 UTC, povolev15 submitted a review, later dismissed

2023-09-13 12:43 UTC, netopyr reviewed
We need to be careful when enabling or changing tests. They need to continue to work with the mono code.

@tinker-michaelj, can you please weight in?

2023-09-13 12:52 UTC, natanasow commented
> We need to be careful when enabling or changing tests. They need to continue to work with the mono code.
> 
> @tinker-michaelj, can you please weight in?

Just ran them against the mono repo and they are working as expected. Good to know to not enable more tests and to be more strict with the current ones. Thank :pray: .

2023-09-14 13:47 UTC, natanasow commented
@netopyr @tinker-michaelj are we ready to merge this or we're waiting for more approvals?

2023-09-14 14:08 UTC, tinker-michaelj requested changes
I think in this case we should keep the test passing as-is.

2023-09-14 15:06 UTC, natanasow commented
> I think in this case we should keep the test passing as-is.

Done.

2023-09-15 12:34 UTC, natanasow commented on hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenManagementSpecsStateful.java
> +                        cryptoTransfer(tinyBarsFromTo(GENESIS, ADDRESS_BOOK_CONTROL, ONE_HUNDRED_HBARS)),
Okay.

2023-09-16 13:08 UTC, natanasow commented on hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenManagementSpecsStateful.java
> +                        cryptoTransfer(tinyBarsFromTo(GENESIS, ADDRESS_BOOK_CONTROL, ONE_HUNDRED_HBARS)),
Did you double-check it?

2023-09-16 13:49 UTC, netopyr commented on hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenManagementSpecsStateful.java
> +                        cryptoTransfer(tinyBarsFromTo(GENESIS, ADDRESS_BOOK_CONTROL, ONE_HUNDRED_HBARS)),
Yes, privileged transactions like this one are free. It should not be needed to transfer Hbar to `ADDRESS_BOOK_CONTROL`. One of the PRs I reviewed recently contained a fix. Not sure which one, though. 🙂 But I think I marked you there.

2023-09-17 08:54 UTC, natanasow commented on hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenManagementSpecsStateful.java
> +                        cryptoTransfer(tinyBarsFromTo(GENESIS, ADDRESS_BOOK_CONTROL, ONE_HUNDRED_HBARS)),
I didn't receive any notification/email :confused:. Reverted the change, pulled develop into this branch and all tests are green now, so we are ready for merge, right?

2023-09-18 07:07 UTC, netopyr approved these changes
LGTM

2023-09-18 07:08 UTC, netopyr commented on hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenManagementSpecsStateful.java
> +                        cryptoTransfer(tinyBarsFromTo(GENESIS, ADDRESS_BOOK_CONTROL, ONE_HUNDRED_HBARS)),
Right. As soon as @tinker-michaelj unblocks the PR, we can merge it.

2023-09-19 14:57 UTC, merged