Resolve `Issue1741Suite` errors
hashgraph/hedera-services pull request #8850
Opened 2023-09-25 05:58 UTC by natanasow

**Description**:

We have the following test suite Issue1741Suite that has problems when it's running against the modularization codebase.

**Solution**:

Resolve issues with the test suite. When ready add @hapitest annotations to the passing tests.

**Related issue(s)**:

Fixes #8763

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-09-25 14:49 UTC, netopyr requested changes
The test currently fails because of our unstable test environment. I just ran the test with the fixes to the test environment applied and it succeeded without changes. Please wait with this PR until the test environment was fixed.

2023-09-26 11:47 UTC, netopyr commented on hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/issues/Issue1741Suite.java
> +                        .hasCostAnswerPrecheck(INSUFFICIENT_PAYER_BALANCE));
This change is not needed.

2023-09-26 11:51 UTC, natanasow commented on hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/issues/Issue1741Suite.java
> +                        .hasCostAnswerPrecheck(INSUFFICIENT_PAYER_BALANCE));
Reverted.

2023-09-26 11:52 UTC, netopyr approved these changes
LGTM

2023-09-26 12:30 UTC, merged