implement system contracts for mint
hashgraph/hedera-services pull request #8856
Opened 2023-09-25 08:01 UTC by dikel

**Description**:
Implementation for HTS `MINT_UNITS` and `MINT_NFTS` functions

1. Created `FungibleMintCall` and `NonFungbileMintCall` both implementing `MintCall` interface
2. Added `newTotalSupply` to `TokenMintRecordBuilder`
3. Created MintXTest for both fungibles and NFTs
4. Written unit tests

**Related issue(s)**:

Fixes #8577 
Fixes #8578

2023-09-27 14:46 UTC, agadzhalov commented on hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/mint/MintTranslator.java
> +            @NonNull final org.hyperledger.besu.datatypes.Address sender,
we can remove `org.hyperledger.besu.datatypes.` and leave it just `Address` as we have the import on top

2023-09-27 14:46 UTC, agadzhalov commented on hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/mint/MintTranslator.java
> +            @NonNull final org.hyperledger.besu.datatypes.Address sender,
again we can remove `org.hyperledger.besu.datatypes.` and leave it just `Address` as we have the import on top

2023-09-27 14:59 UTC, agadzhalov commented on hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/mint/NonFungibleMintCall.java
> +    private TransactionBody syntheticMintUnits(@NonNull final TokenID tokenId, final List<Bytes> metadata) {
we should rename `syntheticMintUnits` to smth like `syntheticMintNfts`

2023-10-02 15:34 UTC, tinker-michaelj requested changes
Overall looks great; but I think we should be able to implement the `MintTranslator` to return an instance of `DispatchForResponseCodeHtsCall`  (as [here](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/associations/AssociationsTranslator.java#L68)) instead of having more one-off implementations of `HtsCall`.

2023-10-02 16:35 UTC, lukelee-sl commented on hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/mint/MintTranslatorTest.java
> +    }
Can the `callFrom` method be tested?

2023-10-03 09:26 UTC, dikel commented on hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/mint/MintTranslatorTest.java
> +    }
It is tested in `HtsCallAttemptTest`

2023-10-04 01:18 UTC, tinker-michaelj approved these changes
This looks great, tyvm @dikel !

2023-10-04 01:58 UTC, merged