Resolve BlockSuite errors
hashgraph/hedera-services pull request #9101
Opened 2023-10-06 12:44 UTC by natanasow

**Description**:

**Related issue(s)**:

Fixes #9100

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-10-09 03:00 UTC, tinker-michaelj requested changes
We want this suite to pass, but it is [currently failing](https://scans.gradle.com/s/lnywjqdmjjbdo/tests/task/:test-clients:hapiTest/details/com.hedera.services.bdd.suites.block.BlockSuite/blck003ReturnsTimestampOfTheBlock?top-execution=1).

2023-10-09 17:22 UTC, mhess-swl approved these changes

2023-10-10 20:10 UTC, rbair23 submitted a review, later dismissed

2023-10-11 01:50 UTC, tinker-michaelj submitted a review, later dismissed
LGTM

2023-10-11 15:51 UTC, mhess-swl approved these changes
LGTM but unit tests failed, possibly due to merge with `develop`

2023-10-11 17:37 UTC, mhess-swl approved these changes

2023-10-11 20:48 UTC, merged