Fix ApproveAllowanceSuite tests
hashgraph/hedera-services pull request #9649
Opened 2023-11-03 12:13 UTC by thenswan

**Description**:
Fix ApproveAllowanceSuite tests

**Related issue(s)**:
Fixes #9357

2023-11-08 16:31 UTC, tinker-michaelj commented on hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/ClassicGrantApprovalCall.java
> +        return EncodingFacade.LogBuilder.logBuilder()
⚠️ We don't want to leave any dependency on the `mono-service` module floating around; so we need to re-create this utility somewhere in the `contract-service-impl` module.

2023-11-08 16:34 UTC, tinker-michaelj requested changes
Overall great work! 🙌 

Two items:
  1. _(Blocking)_ We need to re-create `EncodingFacade` utilities in `contract-service-impl` so we don't have lingering dependencies on mono-service.
  2. _(Nice-to-have)_ Can we add to the `HtsCall` interface a default method,
 
```
    default PricedResult execute(MessageFrame frame) {
       return execute(); 
    }
```

so this PR doesn't have to change all the files for `HtsCall` implementations that don't actually _need_ the `MessageFrame`?

2023-11-09 12:55 UTC, thenswan commented
Hey @tinker-michaelj, I've addressed your points 🙂

2023-11-09 16:05 UTC, tinker-michaelj approved these changes
Awesome, tyvm @thenswan

2023-11-10 07:03 UTC, merged