09427: TokenAndTypeCheckSuite tests fix.
hashgraph/hedera-services pull request #9778
Opened 2023-11-08 21:09 UTC by ilko-iliev-lime

**Description**:
Purpose of the PR is fixing the TokenAndTypeCheckSuite. Problems with the `checkTokenAndTypeNegativeCases` were the following: 

1. In case of a call with invalid token ID to the IsTokenCall class, the status of the result was INVALID_TOKEN_ID, which doesn't match the mono output (success in all cases and false on the isToken field). 
2. In case of a call with invalid token ID to the TokenTypeCall class, the status of the result was REVERTED_SUCCESS, which is a status which overrides the correct one after it is returned, so I had to override the execute function. 

**Related issue(s)**:

Fixes #9427 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-11-09 17:48 UTC, tinker-michaelj commented
Ah looks like we are missing verified signoffs on commits here.

2023-11-10 14:42 UTC, jeromy-cannon approved these changes

2023-11-10 16:18 UTC, jsync-swirlds commented
This has a bad merge and is rewriting several commits already present on develop (which is why the reviewer set expanded).
That needs to be fixed before trying to merge to develop.

2023-11-10 20:42 UTC, jsync-swirlds requested changes
Please fix the cross-merge issue noted above prior to merge.

2023-11-13 09:09 UTC, closed without merging